version: '3.6'

# Services
services:
  fingerprint_service:
    container_name: fingerprint_service
    volumes:
        - ./main:/main
        - ./config/fdxsdkpro:/fdxsdkpro
        - /dev/bus/usb:/dev/bus/usb
    build:
        context: .
        dockerfile: dockerfiles/FingerPrint.Dockerfile
    privileged: true
    tty: true
    restart: always
    ports:
        - "5000:5000"
    env_file:
        - .env.dev